# Generated by Django 3.1.2 on 2021-12-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20211203_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='creator',
            field=models.CharField(blank=True, default='Admin', max_length=255),
        ),
    ]
